//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSFrame.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSFrame.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ; Global
        ///[Global]
        ///Placeholder=0
        ///
        ///; UI,Asset文件夹下的路径，UI只能在Resources下面，例如在Asset/Resources/UI下面，只需要填写Resources/UI
        ///[UI]
        ///PanelPath=
        ///ItemPath=
        ///
        ///;UI脚本,Asset文件夹下的路径，例如在Asset/Script/Code下面，只需要填写Script/Code
        ///[UIScript]
        ///PanelGeneratedScriptPath=
        ///ItemGeneratedScriptPath=
        ///PanelScriptPath=
        ///ItemScriptPath=
        ///PanelDataModelPath=
        ///ItemDataModelPath=
        ///
        ///;导出游戏物体名称前缀对应的类型，慎重修改
        ///[UIExport]
        ///btn_=Button
        ///img_=Image
        ///txt_=Text
        ///txtp_=TextPlus
        ///inp_=InputField
        ///srect_=ScrollRect
        ///sbar_=Scrollbar
        ///tog_=Toggle
        ///sli_=Slide [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ConfigTemplate {
            get {
                return ResourceManager.GetString("ConfigTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //------------------------------------------------------------------------------------------------------------
        /////-----------------------------------generate file {GeneratedTime}----------------------------------------
        /////------------------------------------------------------------------------------------------------------------
        ///using TSFrame.MVVM;
        ///using TSFrame.UI;
        ///using UnityEngine;
        ///using UnityEngine.UI;
        ///
        ///public partial class {ClassName} : UIItem
        ///{
        ///    public override string UIPath =&gt; &quot;{UIPath}&quot;;        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ItemTemplate {
            get {
                return ResourceManager.GetString("ItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using TSFrame;
        ///using TSFrame.MVVM;
        ///using UnityEngine;
        ///
        ///public sealed class {ClassName} : BindingModel
        ///{
        ///
        ///} 的本地化字符串。
        /// </summary>
        internal static string ModelTemplate {
            get {
                return ResourceManager.GetString("ModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //------------------------------------------------------------------------------------------------------------
        /////-----------------------------------generate file {GeneratedTime}----------------------------------------
        /////------------------------------------------------------------------------------------------------------------
        ///using TSFrame.MVVM;
        ///using TSFrame.UI;
        ///using UnityEngine;
        ///using UnityEngine.UI;
        ///
        ///public partial class {ClassName} : UIPanel
        ///{
        ///    public override string UIPath =&gt; &quot;{UIPath}&quot;; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PanelTemplate {
            get {
                return ResourceManager.GetString("PanelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用步骤：
        ///  1.请现在项目目录找到config文件配置PanelPath，
        ///    ItemPath，PanelScriptPath，ItemScriptPath,
        ///    PanelGeneratedScriptPath,ItemGeneratedScriptPath
        ///	PanelDataModelPath,ItemDataModelPath
        ///    路径进行配置
        ///  2.请根据命名习惯配置UIExport参数：前缀=类型
        ///  3.请将需要导出的GameObject的Tag设置为Export 的本地化字符串。
        /// </summary>
        internal static string UIDescription {
            get {
                return ResourceManager.GetString("UIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using TSFrame;
        ///using TSFrame.MVVM;
        ///using TSFrame.UI;
        ///using UnityEngine;
        ///using UnityEngine.UI;
        ///
        ///
        ///public partial class {ClassName}
        ///{
        ///    [Inject]
        ///    private {ModelClass} _{ModelClassName};
        ///
        ///    protected override void OnCreate()
        ///    {
        ///        AddListener();
        ///    }
        ///
        ///    protected override void OnDestroy()
        ///    {
        ///        RemoveListener();
        ///    }
        ///
        ///    #region Listener
        ///    private void AddListener()
        ///    {
        ///
        ///    }
        ///    private void RemoveList [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UITemplate {
            get {
                return ResourceManager.GetString("UITemplate", resourceCulture);
            }
        }
    }
}
